# Modelagem Conceitual #

# Pokedex #

Lista de Pokemons:

Numéro da Pokedex: Caracter (4)
Nome: Caracter (14)
Peso Médio: Float 
Altura Média: Float
Tipo: Caracter (15)
Subtipo: Caracter (15)
Fraquezas: Caracter (70)
Evolução: Caracter (100)
Geração: Caracter (3)

# Até aqui é a Modelagem Física#

Create Database Pokedex;
Use Pokedex;

CREATE TABLE Pokemon(
    `Numero da Pokedex` CHAR(4),
    Nome VARCHAR(14),
    `Peso Médio` Float COMMENT 'Em kilogramas',
    `Altura Média` Float COMMENT 'Em metros',
    Tipo VARCHAR(15),
    Subtipo VARCHAR(15),
    Fraquezas VARCHAR(70),
    Evolução VARCHAR(100),
    Geração VARCHAR(3)
);

INSERT INTO Pokemon (`Numero da Pokedex`, Nome, `Peso Médio`, `Altura Média` , Tipo, Subtipo, Fraquezas, Evolução, Geração)

VALUES                                            # Primeira Geração #
        (1, 'Bulbasaur', 6.9, 0.7, 'Planta', 'Venenoso', 'Fogo, Psiquico, Gelo e Voador', 'Ivysaur', '1'),
        (2, 'Ivysaur', 13.0 , 1.0, 'Planta', 'Venenoso', 'Fogo, Psiquico, Gelo e Voador', 'Venosaur', '1'),
	(3, 'Venosaur', 100.0, 2.0, 'Planta', 'Venenoso', 'Fogo, Psiquico, Gelo e Voador', 'N/A', '1'),
	(4, 'Charmander', 8.5, 0.6, 'Fogo', 'Nenhum', 'Agua, Terra e Pedra', 'Charmeleon', '1'),
	(5, 'Charmeleon', 19.0, 1.1, 'Fogo', 'Nenhum', 'Agua, Terra e Pedra', 'Charizard', '1'),
	(6, 'Charizard', 90.5, 1.7, 'Fogo', 'Voador', 'Agua, Pedra e Elétrico', 'N/A', '1'),
	(7, 'Squirtle', 9.0, 0.5, 'Agua', 'Nenhum', 'Planta e Elétrico', 'Wartortle', '1'),
	(8, 'Wartortle', 22.5, 1.0, 'Agua', 'Nenhum', 'Planta e Elétrico', 'Blastoise', '1'),
	(9, 'Blastoise', 85.5, 1.6, 'Agua', 'Nenhum', 'Planta e Elétrico', 'N/A', '1'),
	(10, 'Caterpie', 2.9, 0.3, 'Inseto', 'Nenhum', 'Fogo, Voador e Pedra', 'Metapod', '1'),
	(11, 'Metapod', 9.9, 0.7, 'Inseto', 'Nenhum', 'Fogo, Voador e Pedra', 'Butterfree', '1'),
	(12, 'Butterfree', 32.0, 1.1, 'Inseto', 'Voador', 'Fogo, Voador, Elétrico, Gelo e Pedra', 'N/A', '1'),
	(13, 'Weedle', 3.2, 0.3, 'Inseto', 'Venenoso', 'Fogo, Psiquico, Voador e Pedra', 'Kakuna', '1'),
	(14, 'Kakuna', 10.0, 0.6, 'Inseto', 'Venenoso', 'Fogo, Psiquico, Voador e Pedra', 'Beedrill', '1'),
	(15, 'Beedrill', 29.5, 1.0, 'Inseto', 'Venenoso', 'Fogo, Psiquico, Voador e Pedra', 'N/A', '1'),
	(16, 'Pidgey', 1.8, 0.3, 'Normal', 'Voador', 'Elétrico, Gelo e Pedra', 'Pidgeotto', '1'),
	(17, 'Pidgeotto', 30.0, 1.1, 'Normal', 'Voador', 'Elétrico, Gelo e Pedra', 'Pidgeot', '1'),
	(18, 'Pidgeot', 39.5, 1.5, 'Normal', 'Voador', 'Elétrico, Gelo e Pedra', 'N/A', '1'),
	(19, 'Ratata', 3.5, 0.3, 'Normal', 'Nenhum', 'Lutador', 'Raticate', '1'),
	(20, 'Raticate', 18.5, 0.7, 'Normal', 'Nenhum', 'Lutador', 'N/A', '1'),
	(21, 'Spearow', 2.0, 0.3, 'Normal', 'Voador', 'Elétrico, Gelo e Pedra', 'Fearow', '1'),
	(22, 'Fearow', 38.0, 1.2, 'Normal', 'Voador', 'Elétrico, Gelo e Pedra', 'N/A', '1'),
	(23, 'Ekans', 6.9, 2.0, 'Venenoso', 'Nenhum', 'Psiquico e Terra', 'Arbok', '1'),
	(24, 'Arbok', 65.0, 3.5, 'Venenoso', 'Nenhum', 'Psiquico e Terra', 'N/A', '1'),
	(25, 'Pikachu', 6.0, 0.4, 'Elétrico', 'Nenhum', 'Terra', 'Raichu', '1'),
	(26, 'Raichu', 30.0, 0.8, 'Elétrico', 'Nenhum', 'Terra', 'N/A', '1'),
	(27, 'Sandshrew', 12.0, 0.6, 'Terra', 'Nenhum', 'Agua, Planta e Gelo', 'Sandslash', '1'),
	(28, 'Sandslash', 29.5, 1.0, 'Terra', 'Nenhum', 'Agua, Planta e Gelo', 'N/A', '1'),
	(29, 'Nidoran Fêmea', 7.0, 0.4, 'Venenoso', 'Nenhum', 'Psiquico e Terra', 'Nidorina', '1'),
	(30, 'Nidorina', 20.0, 0.8, 'Venenoso', 'Nenhum', 'Psiquico e Terra', 'Nidoqueen', '1'),
	(31, 'Nidoqueen', 60.0, 1.3, 'Venenoso', 'Terra', 'Psiquico, Terra, Gelo e Agua', 'N/A', '1'),
	(32, 'Nidoran Macho', 9.0, 0.5, 'Venenoso', 'Nenhum', 'Psiquico e Terra', 'Nidorino', '1'),
	(33, 'Nidorino', 19.5, 0.9, 'Venenoso', 'Nenhum', 'Psiquico e Terra', 'Nidoking', '1'),
	(34, 'Nidoking', 19.5, 0.9, 'Venenoso', 'Terra', 'Psiquico, Terra, Gelo e Agua', 'N/A', '1'),
	(35, 'Clefairy', 7.5, 0.6, 'Fada', 'Nenhum', 'Metal e Venenoso', 'Clefable', '1'),
	(36, 'Clefable', 7.5, 0.6, 'Fada', 'Nenhum', 'Metal e Venenoso', 'N/A', '1'),
	(37, 'Vulpix', 9.9, 0.6, 'Fogo', 'Nenhum', 'Agua, Terra e Pedra', 'Ninetales', '1'),
	(38, 'Ninetales', 19.9, 1.1, 'Fogo', 'Nenhum', 'Agua, Terra e Pedra', 'N/A', '1'),
	(39, 'Jigglypuff', 5.5, 0.5, 'Normal', 'Fada', 'Metal e Venenoso', 'Wigglytuff', '1'),
	(40, 'Wigglytuff', 12.0, 1.0, 'Normal', 'Fada', 'Metal e Venenoso', 'N/A', '1'),
	(41, 'Zubat', 7.5, 0.8, 'Venenoso', 'Voador', 'Psiquico, Elétrico, Gelo e Pedra', 'Golbat', '1'),
	(42, 'Golbat', 55.0, 1.6, 'Venenoso', 'Voador', 'Psiquico, Elétrico, Gelo e Pedra', 'Crobat', '1'),
	(43, 'Odish', 5.4, 0.5, 'Planta', 'Venenoso', 'Fogo, Psiquico, Gelo e Voador', 'Gloom', '1'),
	(44, 'Gloom', 8.6, 0.8, 'Planta', 'Venenoso', 'Fogo, Psiquico, Gelo e Voador', 'Vileplume ou Bellossom','1'),
	(45, 'Vileplume', 18.6, 1.2, 'Planta', 'Venenoso', 'Fogo, Psiquico, Gelo e Voador', 'N/A','1'),
	(46, 'Paras', 5.4, 0.3, 'Inseto', 'Planta', 'Fogo, Voador, Gelo, Venenoso, Pedra e Inseto', 'Parasect','1'),
	(47, 'Parasect', 29.5, 1.0, 'Inseto', 'Planta', 'Fogo, Voador, Gelo, Venenoso, Pedra e Inseto', 'N/A','1'),
	(48, 'Venonat', 30.0, 1.0, 'Inseto', 'Venenoso', 'Fogo, Voador, Psiquico e Pedra', 'Venomoth','1'),
	(49, 'Venomoth', 12.5, 1.5, 'Inseto', 'Venenoso', 'Fogo, Voador, Psiquico e Pedra', 'N/A','1'),
	(50, 'Diglett', 0.8, 0.2, 'Terra', 'Nenhum', 'Agua, Planta e Gelo', 'Dugtrio','1'),
	(51, 'Dugtrio', 33.3, 0.7, 'Terra', 'Nenhum', 'Agua, Planta e Gelo', 'N/A','1'),
	(52, 'Meowth', 4.2, 0.4, 'Normal', 'Nenhum', 'Lutador','Persian','1'),
	(53, 'Persian', 32.0, 1.0, 'Normal', 'Nenhum', 'Lutador','N/A','1'),
	(54, 'Psyduck', 19.6, 0.8, 'Agua', 'Nenhum', 'Planta e Elétrico','Golduck','1'),
	(55, 'Golduck', 76.6, 1.7, 'Agua', 'Nenhum', 'Planta e Elétrico','N/A','1'),
	(56, 'Mankey', 28.0, 0.5, 'Lutador', 'Nenhum', 'Psiquico, Voador e Fada','Primeape','1'),
	(57, 'Primeape', 32.0, 1.0, 'Lutador', 'Nenhum', 'Psiquico, Voador e Fada','Annihilape','1'),
	(58, 'Growlithe', 19.0, 0.7, 'Fogo', 'Nenhum', 'Agua, Terra e Pedra','Arcanine','1'),
	(59, 'Arcanine', 155.0, 1.9, 'Fogo', 'Nenhum', 'Agua, Terra e Pedra','N/A','1'),
	(60, 'Poliwag', 12.4, 0.6, 'Agua', 'Nenhum', 'Planta e Elétrico','Poliwhirl','1'),
	(61, 'Poliwhirl', 20.0, 1.0, 'Agua', 'Nenhum', 'Planta e Elétrico','Poliwrath ou Politoed','1'),
	(62, 'Poliwrath', 54.0, 1.3, 'Agua', 'Nenhum', 'Planta e Elétrico','N/A','1'),
	(63, 'Abra', 19.5, 0.9, 'Psiquico', 'Nenhum', 'Fantasma, Escuridão e Inseto','Kadabra','1'),
	(64, 'Kadabra', 56.5, 1.3, 'Psiquico', 'Nenhum', 'Fantasma, Escuridão e Inseto','Alakazam','1'),
	(65, 'Alakazam', 48.0, 1.5, 'Psiquico', 'Nenhum', 'Fantasma, Escuridão e Inseto','N/A','1'),
	(66, 'Machop', 19.5, 0.8, 'Lutador', 'Nenhum', 'Psiquico, Voador e Fada','Machoke','1'),
	(67, 'Machoke', 70.5, 1.5, 'Lutador', 'Nenhum', 'Psiquico, Voador e Fada','Machamp','1'),
	(68, 'Machamp', 130.0, 1.6, 'Lutador', 'Nenhum', 'Psiquico, Voador e Fada','N/A','1'),
	(69, 'Bellsprout', 4.0, 0.7, 'Planta', 'Venenoso', 'Fogo, Psiquico, Gelo e Voador', 'Weepinbell', '1'),
	(70, 'Weepinbell', 6.4, 1.0, 'Planta', 'Venenoso', 'Fogo, Psiquico, Gelo e Voador', 'Victreebel', '1'),
	(71, 'Victreebel', 15.5, 1.7, 'Planta', 'Venenoso', 'Fogo, Psiquico, Gelo e Voador', 'N/A', '1'),
	(72, 'Tentacool', 45.5, 0.9, 'Agua', 'Venenoso', 'Terra, Elétrico e Psiquico', 'Tentacruel', '1'),
	(73, 'Tentacool', 45.5, 0.9, 'Agua', 'Venenoso', 'Terra, Elétrico e Psiquico', 'N/A', '1'),
	(74, 'Geodude', 20.0, 0.4, 'Pedra', 'Terra', 'Metal, Lutador, Agua, Gelo, Planta e Terra', 'Graveler','1'),
	(75, 'Graveler', 105.0, 1.0, 'Pedra', 'Terra', 'Metal, Lutador, Agua, Gelo, Planta e Terra', 'Golem','1'),
	(76, 'Golem', 300.0, 1.4, 'Pedra', 'Terra', 'Metal, Lutador, Agua, Gelo, Planta e Terra', 'N/A','1'),
	(77, 'Ponyta', 30.0, 1.0, 'Fogo', 'Nenhum', 'Agua, Terra e Pedra', 'Rapidash', '1'),
	(78, 'Rapidash', 95.0, 1.7, 'Fogo', 'Nenhum', 'Agua, Terra e Pedra', 'N/A', '1'),
	(79, 'Slowpoke', 36.0, 1.2, 'Agua', 'Psiquico', 'Fantasma, Escuridão, Planta, Elétrico e Inseto', 'Slowbro ou Slowking', '1'),
	(80, 'Slowbro', 78.5, 1.6, 'Agua', 'Psiquico', 'Fantasma, Escuridão, Planta, Elétrico e Inseto', 'N/A', '1'),
	(81, 'Magnemite', 6.0, 0.3, 'Elétrico', 'Metal', 'Fogo, Lutador e Terra', 'Magneton', '1'),
	(82, 'Magneton', 60.0, 1.0, 'Elétrico', 'Metal', 'Fogo, Lutador e Terra', 'Magnezone', '1'),
	(83, 'Farfetch’d', 15.0, 0.8, 'Normal', 'Voador', 'Elétrico, Gelo e Pedra', 'Sirfetch’d', '1'),
	(84, 'Doduo', 39.2, 1.4, 'Normal', 'Voador', 'Elétrico, Gelo e Pedra', 'Dodrio', '1'),
	(85, 'Dodrio', 85.2, 1.8, 'Normal', 'Voador', 'Elétrico, Gelo e Pedra', 'N/A', '1'),
        (86, 'Seel', 90.0, 1.1, 'Agua', 'Nenhum', 'Planta e Elétrico', 'Dewgong', '1'),
	(87, 'Dewgong', 120.0, 1.7, 'Agua', 'Nenhum', 'Planta, Elétrico, Lutador e Pedra', 'Dewgong', '1'),
        (88, 'Grimer', 30.0, 0.9, 'Venenoso', 'Nenhum', 'Psiquico e Terra', 'Muk', '1'),
	(89, 'Muk', 30.0, 1.2, 'Venenoso', 'Nenhum', 'Psiquico e Terra', 'N/A', '1'),
	(90, 'Shellder', 4.0, 0.3, 'Agua', 'Nenhum', 'Planta e Elétrico', 'Cloyster', '1'),
	(91, 'Cloyster', 132.5, 1.5, 'Agua', 'Gelo', 'Planta, Elétrico, Lutador e Pedra', 'N/A', '1'),
	(92, 'Gastly', 0.1, 1.3, 'Fantasma', 'Venenoso', 'Fantasma, Escuridão, Psiquico e Terra', 'Haunter', '1'),
	(93, 'Haunter', 0.1, 1.3, 'Fantasma', 'Venenoso', 'Fantasma, Escuridão, Psiquico e Terra', 'Gengar', '1'),
	(94, 'Gengar', 40.5, 1.5, 'Fantasma', 'Venenoso', 'Fantasma, Escuridão, Psiquico e Terra', 'N/A', '1'),
	(95, 'Onix', 210.0, 8.8, 'Pedra', 'Terra', 'Metal, Lutador, Agua, Gelo, Planta e Terra', 'Steelix','1'),
	(96, 'Drowzee', 32.4, 1.0, 'Psiquico', 'Nenhum', 'Fantasma, Escuridão e Inseto','Hypno','1'),
	(97, 'Hypno', 75.6, 1.6, 'Psiquico', 'Nenhum', 'Fantasma, Escuridão e Inseto','N/A','1'),
	(98, 'Krabby', 6.5, 0.4, 'Agua', 'Nenhum', 'Planta e Elétrico', 'Kingler', '1'),
	(99, 'Kingler', 60.0, 1.3, 'Agua', 'Nenhum', 'Planta e Elétrico', 'N/A', '1'),
	(100, 'Voltorb', 10.4, 0.5, 'Elétrico', 'Nenhum', 'Terra', 'Electrode', '1'),
	(101, 'Electrode', 66.6, 1.2, 'Elétrico', 'Nenhum', 'Terra', 'N/A', '1'),
	(102, 'Exeggcute', 2.5, 0.4, 'Planta', 'Psiquico', 'Fantasma, Fogo, Voador, Gelo, Escuridão, Venenoso, Inseto', 'Exeggutor', '1'),
	(103, 'Exeggutor', 120.0, 2.0, 'Planta', 'Psiquico', 'Fantasma, Fogo, Voador, Gelo, Escuridão, Venenoso, Inseto', 'N/A', '1'),
	(104, 'Cubone', 6.5, 0.4, 'Terra', 'Nenhum', 'Agua, Planta e Gelo', 'Marowak', '1'),
	(105, 'Marowak', 45.0, 1.0, 'Terra', 'Nenhum', 'Agua, Planta e Gelo', 'N/A', '1'),
	(106, 'Hitmonlee', 49.8, 1.5, 'Lutador', 'Nenhum', 'Psiquico, Voador e Fada','N/A','1'),
	(107, 'Hitmonchan', 50.2, 1.4, 'Lutador', 'Nenhum', 'Psiquico, Voador e Fada','N/A','1'),
	(108, 'Lickitung', 65.5, 1.2, 'Normal', 'Nenhum', 'Lutador','Lickilicky','1'),
	(109, 'Grimer', 1.0, 0.6, 'Venenoso', 'Nenhum', 'Psiquico e Terra', 'Weezing', '1'),
	(110, 'Weezing', 9.5, 1.2, 'Venenoso', 'Nenhum', 'Psiquico e Terra', 'N/A', '1'),
	(111, 'Rhyhorn', 115.0, 1.0, 'Pedra', 'Terra', 'Metal, Lutador, Agua, Gelo, Planta e Terra', 'Rhydon','1'),
	(112, 'Rhydon', 125.0, 1.9, 'Pedra', 'Terra', 'Metal, Lutador, Agua, Gelo, Planta e Terra', 'Rhyperior','1'),
	(113, 'Chansey', 34.6, 1.1, 'Normal', 'Nenhum', 'Lutador','Blissey','1'),
	(114, 'Tangela', 35.0, 1.0, 'Planta', 'Nenhum', 'Fogo, Voador, Gelo, Venenoso e Inseto', 'Tangrowth', '1'),
	(115, 'Kangaskhan', 80.0, 2.2, 'Normal', 'Nenhum', 'Lutador','N/A','1'),
	(116, 'Horsea', 8.0, 0.4, 'Agua', 'Nenhum', 'Planta e Elétrico', 'Seadra', '1'),
	(117, 'Seadra', 25.0, 1.2, 'Agua', 'Nenhum', 'Planta e Elétrico', 'Kingdra', '1'),
	(118, 'Goldeen', 15.0, 0.6, 'Agua', 'Nenhum', 'Planta e Elétrico', 'Seaking', '1'),
	(119, 'Seaking', 39.0, 1.3, 'Agua', 'Nenhum', 'Planta e Elétrico', 'N/A', '1'),
	(120, 'Staryu', 34.5, 0.8, 'Agua', 'Nenhum', 'Planta e Elétrico', 'Starmie', '1'),
	(121, 'Starmie', 80.0, 1.1, 'Agua', 'Psiquico', 'Fantasma, Escuridão, Planta, Elétrico e Inseto', 'N/A', '1'),
	(122, 'Mr Mime', 54.5, 1.3, 'Psiquico', 'Fada', 'Fantasma, Metal e Venenoso','N/A','1'),
	(123, 'Scyther', 56.0, 1.5, 'Inseto', 'Voador', 'Fogo, Voador, Elétrico, Gelo e Pedra', 'Scizor ou Kleavor', '1'),
	(124, 'Jynx', 40.6, 1.4, 'Gelo', 'Psiquico', 'Metal, Fantasma, Fogo, Escuridão, Pedra e Inseto', 'N/A', '1'),
	(125, 'Electabuzz', 30.0, 1.1, 'Elétrico', 'Nenhum', 'Terra', 'Electivire', '1'),
	(126, 'Magmar', 44.5, 1.3, 'Fogo', 'Nenhum', 'Agua, Terra e Pedra', 'Magmortar', '1'),
	(127, 'Pinsir', 55.0, 1.5, 'Inseto', 'Nenhum', 'Fogo, Voador e Pedra', 'N/A', '1'),
	(128, 'Tauros', 88.4, 1.4, 'Normal', 'Nenhum', 'Lutador','N/A','1'),
	(129, 'Magikarp', 10.0, 0.9, 'Agua', 'Nenhum', 'Planta e Elétrico', 'Gyarados', '1'),
	(130, 'Gyarados', 235.0, 6.5, 'Agua', 'Voador', 'Elétrico e Pedra', 'N/A', '1'),
	(131, 'Lapras', 220.0, 2.5, 'Agua', 'Gelo', 'Planta, Elétrico, Lutador e Pedra', 'Gyarados', '1'),
	(132, 'Dito', 4.0, 0.3, 'Normal', 'Nenhum', 'Lutador','N/A','1'),
	(133, 'Eevee', 6.5, 0.3, 'Normal', 'Nenhum', 'Lutador','Vaporeon, Jolteon, Flareon,, Espeon, Umbreon, Leafeon, Glaceon ou Sylveon','1'),
        (134, 'Vaporeon', 29.0, 1.0, 'Agua', 'Nenhum', 'Planta e Elétrico', 'N/A', '1'),	
	(135, 'Jolteon', 24.5, 0.8, 'Elétrico', 'Nenhum', 'Terra', 'N/A', '1'),	
	(136, 'Flareon', 25.0, 0.9, 'Fogo', 'Nenhum', 'Agua, Terra e Pedra', 'N/A', '1'),	
	(137, 'Porygon', 36.5, 0.8, 'Normal', 'Nenhum', 'Lutador', 'Porygon2', '1'),
        (138, 'Omanyte', 7.5, 0.4, 'Pedra', 'Agua', 'Planta, Elétrico, Lutador e Terra', 'Omastar', '1'),	
	(139, 'Omastar', 35.0, 1.0, 'Pedra', 'Agua', 'Planta, Elétrico, Lutador e Terra', 'N/A', '1'),	
	(140, 'Kabuto', 11.5, 0.5, 'Pedra', 'Agua', 'Planta, Elétrico, Lutador e Terra', 'Kabutops', '1'),
	(141, 'Kabutops', 40.5, 1.3, 'Pedra', 'Agua', 'Planta, Elétrico, Lutador e Terra', 'N/A', '1'),
	(142, 'Aerodactyl', 59.0, 1.8, 'Pedra', 'Voador', 'Metal, Agua, Elétrico, Gelo e Pedra', 'N/A', '1'),
	(143, 'Snorlax ', 460.0, 2.1, 'Normal', 'Nenhum', 'Lutador','N/A','1'),
	(144, 'Articuno', 55.4, 1.7, 'Gelo', 'Voador', 'Metal, Fogo, Elétrico e Pedra', 'N/A', '1'),
	(145, 'Zapdos', 52.6, 1.6, 'Elétrico', 'Voador', 'Gelo e Pedra', 'N/A', '1'),
	(146, 'Moltres', 60.0, 2.0, 'Fogo', 'Voador', 'Agua, Elétrico e Pedra', 'N/A', '1'),
	(147, 'Dratini', 3.3, 1.8, 'Dragão', 'Nenhum', 'Fada, Gelo e Dragão', 'Dragonair', '1'),
	(148, 'Dragonair', 16.5, 4.0, 'Dragão', 'Nenhum', 'Fada, Gelo e Dragão', 'Dragonite', '1'),
	(149, 'Dragonite', 210.0, 2.2, 'Dragão', 'Voador', 'Fada, Dragão, Gelo e Pedra', 'N/A', '1'),
	(150, 'Mewtwo', 122.0, 2.0, 'Psiquico', 'Nenhum', 'Fantasma, Escuridão e Inseto','N/A','1'),
	(151, 'Mew', 4.0, 0.4, 'Psiquico', 'Nenhum', 'Fantasma, Escuridão e Inseto','N/A','1'),
	
	                                            # Segunda Geração #

	(152, 'Chikorita', 6.4, 0.9, 'Planta','Nenhum', 'Fogo, Voador, Gelo, Venenoso e Inseto','Bayleef','2'),
	(153, 'Bayleef', 15.8, 1.2, 'Planta', 'Nenhum', 'Fogo, Voador, Gelo, Venenoso e Inseto','Meganium','2'),
	(154, 'Meganium', 100.5, 1.8, 'Planta', 'Nenhum', 'Fogo, Voador, Gelo, Venenoso e Inseto','N/A','2'),
	(155, 'Cyndaquil', 7.9, 0.5, 'Fogo', 'Nenhum', 'Agua, Terra e Pedra', 'Quilava', '2'),
	(156, 'Quilava', 19.0, 0.9, 'Fogo', 'Nenhum', 'Agua, Terra e Pedra', 'Typhlosion', '2'),
	(157, 'Typhlosion', 79.5, 1.7, 'Fogo', 'Nenhum', 'Agua, Terra e Pedra', 'N/A', '2'),
	(158, 'Totodile', 9.5, 0.6, 'Agua', 'Nenhum', 'Planta e Elétrico', 'Croconaw', '2'),
	(159, 'Croconaw', 25.0, 1.1, 'Agua', 'Nenhum', 'Planta e Elétrico', 'Feraligatr', '2'),
	(160, 'Feraligatr', 88.8, 2.3, 'Agua', 'Nenhum', 'Planta e Elétrico', 'N/A', '2'),
	(161, 'Sentret', 6.0, 0.8, 'Normal', 'Nenhum', 'Lutador', 'Furret', '2'),
	(162, 'Furret', 32.5, 1.8, 'Normal', 'Nenhum', 'Lutador', 'N/A', '2'),
	(163, 'Hoothoot', 21.2, 0.7, 'Normal', 'Voador', 'Elétrico, Gelo e Pedra', 'Noctowl', '2'),
	(164, 'Noctowl', 40.8, 1.6, 'Normal', 'Voador', 'Elétrico, Gelo e Pedra', 'N/A', '2'),
	(165, 'Ledyba', 10.8, 1.0, 'Inseto', 'Voador', 'Fogo, Voador, Elétrico, Gelo e Pedra', 'Ledian', '2'),
	(166, 'Ledian', 35.6, 1.4, 'Inseto', 'Voador', 'Fogo, Voador, Elétrico, Gelo e Pedra', 'N/A', '2'),
	(167, 'Spinarak', 8.5, 0.5, 'Inseto', 'Venenoso', 'Fogo, Voador, Psiquico e Pedra',' Ariados','2'),
	(168, 'Ariados', 33.5, 1.1, 'Inseto', 'Venenoso', 'Fogo, Voador, Psiquico e Pedra',  'N/A','2'),
	(169, 'Crobat', 75.0, 1.8, 'Venenoso', 'Voador', 'Psiquico, Elétrico, Gelo e Pedra', 'N/A','2'),
	(170, 'Chinchou', 12.0, 0.5, 'Agua', 'Elétrico', 'Planta e Terra', 'Lanturn', '2'),
	(171, 'Lanturn', 22.5, 1.2, 'Agua', 'Elétrico', 'Planta e Terra', 'N/A', '2'),
	(172, 'Pichu', 2.0, 0.3, 'Elétrico', 'Nenhum', 'Terra', 'Pikachu', '2'),
	(173, 'Cleffa', 3.0, 0.3, 'Fada', 'Nenhum', 'Metal e Venenoso', 'Clefairy', '2'),
	(174, 'Igglybuff', 1.0, 0.3, 'Fada', 'Normal', 'Metal e Venenoso', 'Jigglypuff', '2'),
	(175, 'Togepi', 1.5, 0.3, 'Fada', 'Nenhum', 'Metal e Venenoso', 'Togetic', '2'),
	(176, 'Togetic', 3.2, 0.6, 'Fada', 'Voador', 'Metal, Venenoso, Elétrico, Gelo e Pedra', 'Togekiss', '2'),
	(177, 'Natu', 2.0, 0.2, 'Psiquico', 'Voador', 'Fantasma, Escuridão, Elétrico, Gelo e Pedra', 'Xatu', '2'),
	(178, 'Xatu', 15.0, 1.5, 'Psiquico', 'Voador', 'Fantasma, Escuridão, Elétrico, Gelo e Pedra', 'N/A', '2'),
	(179, 'Mareep', 7.8, 0.6, 'Elétrico', 'Nenhum', 'Terra', 'Flaaffy', '2'),
	(180, 'Flaaffy', 13.3, 0.8, 'Elétrico', 'Nenhum', 'Terra', 'Ampharos', '2'),
	(181, 'Ampharos', 61.5, 1.4, 'Elétrico', 'Nenhum', 'Terra', 'N/A', '2'),
	(182, 'Bellossom', 5.8, 0.4, 'Planta', 'Nenhum', 'Fogo, Voador, Gelo, Venenoso e Inseto','N/A','2'),
	(183, 'Marill', 8.5, 0.4, 'Agua', 'Fada', 'Planta, Elétrico e Venenoso', 'Azumarill', '2'),
	(184, 'Azumarill', 28.5, 0.8, 'Agua', 'Fada', 'Planta, Elétrico e Venenoso', 'N/A', '2'),
	(185, 'Sudowoodo', 38.0, 1.2, 'Pedra', 'Nenhum', 'Agua, Metal, Planta, Lutador e Terra', 'N/A', '2'),
	(186, 'Politoed', 33.9, 1.1, 'Agua', 'Nenhum', 'Planta e Elétrico', 'N/A', '2'),
	(187, 'Hoppip', 0.5, 0.4, 'Planta', 'Voador', 'Fogo, Voador, Gelo, Venenoso e Pedra','Skiploom','2'),
	(188, 'Skiploom', 1.0, 0.6, 'Planta', 'Voador', 'Fogo, Voador, Gelo, Venenoso e Pedra','Jumpluff','2'),
	(189, 'Jumpluff', 3.0, 0.8, 'Planta', 'Voador', 'Fogo, Voador, Gelo, Venenoso e Pedra','N/A','2'),
	(190, 'Aipom', 11.5, 0.8, 'Normal', 'Nenhum', 'Lutador','Ambipom','2'),
	(191, 'Sunkern', 1.8, 0.3, 'Planta', 'Nenhum', 'Fogo, Voador, Gelo, Venenoso e Inseto','Sunflora','2'),
	(192, 'Sunflora', 8.5, 0.8, 'Planta', 'Nenhum', 'Fogo, Voador, Gelo, Venenoso e Inseto','N/A','2'),
	(193, 'Yanma', 38.0, 1.2, 'Inseto', 'Voador', 'Fogo, Voador, Elétrico, Gelo e Pedra', 'Yanmega', '2'),
	(194, 'Wooper', 8.5, 0.4, 'Agua', 'Terra', 'Planta', 'Quagsire', '2'),
	(195, 'Quagsire', 75.0, 1.4, 'Agua', 'Terra', 'Planta', 'N/A', '2'),
	(196, 'Espeon', 26.5, 0.9, 'Psiquico', 'Nenhum', 'Fantasma, Escuridão e Inseto', 'N/A', '2'),
	(197, 'Umbreon', 27.0, 1.0, 'Escuridão', 'Nenhum', 'Fada, Inseto e Lutador', 'N/A', '2'),
	(198, 'Murkrow', 1.1, 0.5, 'Escuridão', 'Voador', 'Fada, Elétrico, Gelo e Pedra', 'Honchkrow', '2'),
	(199, 'Slowking', 79.5, 2.0, 'Agua', 'Psiquico', 'Fantasma, Escuridão, Planta, Elétrico e Inseto', 'N/A', '2'),
	(200, 'Misdreavus', 1.6, 0.7, 'Fantasma', 'Venenoso', 'Fantasma, Escuridão', 'Mismagius', '2'),
	(201, 'Unown', 5.0, 0.5, 'Psiquico', 'Nenhum', 'Fantasma, Escuridão e Inseto', 'N/A', '2'),
	(202, 'Wobbuffet', 28.5, 1.3, 'Psiquico', 'Nenhum', 'Fantasma, Escuridão e Inseto', 'N/A', '2'),
	(203, 'Girafarig', 41.5, 1.5, 'Normal', 'Psiquico', 'Escuridão e Inseto', 'Farigiraf', '2'),
	(204, 'Pineco', 7.2, 0.6, 'Inseto', 'Nenhum', 'Fogo, Voador e Pedra', 'Forretress', '2'),
	(205, 'Forretress', 125.8, 1.2, 'Inseto', 'Metal', 'Fogo', 'N/A', '2'),
	(206, 'Dunsparce', 14.0, 1.5, 'Normal', 'Nenhum', 'Lutador','Dudunsparce','2'),
	(207, 'Gligar', 64.8, 1.1, 'Terra', 'Voador', 'Agua e Gelo','Gliscor','2'),
	(208, 'Steelix', 400.0, 9.2, 'Metal', 'Terra', 'Fogo, Agua, Lutador e Terra', 'N/A','2'),
	(209, 'Snubbull', 7.8, 0.6, 'Fada', 'Nenhum', 'Metal e Venenoso', 'Granbull','2'),
	(210, 'Granbull', 48.7, 1.4, 'Fada', 'Nenhum', 'Metal e Venenoso', 'N/A','2'),
	(211, 'Qwilfish', 3.9, 0.5, 'Agua', 'Venenoso', 'Psiquico Elétrico e Terra', 'Overqwil','2'),
	(212, 'Scizor', 118.0, 1.8, 'Inseto', 'Metal', 'Fogo', 'N/A','2'),
	(213, 'Shuckle', 20.5, 0.6, 'Inseto', 'Pedra', 'Metal, Agua e Pedra', 'N/A','2'),
	(214, 'Heracross', 54.0, 1.5, 'Inseto', 'Lutador', 'Fogo, Psiquico, Voador e Fada', 'N/A','2'),
	(215, 'Sneasel', 28.0, 0.9, 'Escuridão', 'Gelo', 'Metal, Fogo, Lutador, Pedra, Fada e Inseto', 'Weavile','2'),
	(216, 'Teddiursa', 8.8, 0.6, 'Normal', 'Nenhum', 'Lutador','Ursaring','2'),
	(217, 'Ursaring', 125.8, 1.8, 'Normal', 'Nenhum', 'Lutador','Ursaluna','2'),
	(218, 'Slugma', 35.0, 0.7, 'Fogo', 'Nenhum', 'Agua, Terra e Pedra', 'Magcargo', '2'),
	(219, 'Magcargo', 55.0, 0.8, 'Fogo', 'Pedra', 'Agua, Terra, Lutador e Pedra', 'N/A', '2'),
	(220, 'Swinub', 6.5, 0.4, 'Gelo', 'Terra', 'Metal, Fogo, Planta, Agua e Lutador', 'Piloswine', '2'),
	(221, 'Piloswine', 55.8, 1.1, 'Gelo', 'Terra', 'Metal, Fogo, Planta, Agua e Lutador', 'Mamoswine', '2'),
	(222, 'Corsola', 5.0, 0.6, 'Agua', 'Pedra', 'Planta, Elétrico, Lutador e Terra', 'N/A', '2'),
	(223, 'Remoraid', 12.0, 0.6, 'Agua', 'Nenhum', 'Planta e Elétrico', 'Octillery', '2'),
	(224, 'Octillery', 28.5, 0.9, 'Agua', 'Nenhum', 'Planta e Elétrico', 'N/A', '2'),
	(225, 'Delibird', 16.0, 0.9, 'Gelo', 'Voador', 'Metal, Fogo, Elétrico e Pedra', 'N/A', '2'),
	(226, 'Mantine', 220.0, 2.1, 'Agua', 'Voador', 'Elétrico e Pedra', 'N/A', '2'),
	(227, 'Skarmory', 50.5, 1.7, 'Metal', 'Voador', 'Fogo e Elétrico', 'N/A', '2'),
	(228, 'Houndour', 10.8, 0.6, 'Escuridão', 'Fogo', 'Agua, Terra, Lutador e Pedra', 'Houndoom', '2'),
	(229, 'Houndoom', 35.0, 1.4, 'Escuridão', 'Fogo', 'Agua, Terra, Lutador e Pedra', 'N/A', '2'),
	(230, 'Kingdra', 152.0, 1.8, 'Agua', 'Dragão', 'Fada e Dragão', 'N/A', '2'),
	(231, 'Phanpy', 33.5, 0.5, 'Terra', 'Nenhum', 'Agua, Planta e Gelo', 'Donphan', '2'),
	(232, 'Donphan', 120.0, 1.1, 'Terra', 'Nenhum', 'Agua, Planta e Gelo', 'N/A', '2'),
	(233, 'Porygon2', 32.5, 0.6, 'Normal', 'Nenhum', 'Lutador', 'Porygon-Z', '2'),
	(234, 'Stantler', 72.2, 1.4, 'Normal', 'Nenhum', 'Lutador', 'Wyrdeer', '2'),
	(235, 'Smeargle', 58.0, 1.2, 'Normal', 'Nenhum', 'Lutador', 'N/A', '2'),
	(236, 'Tyrogue', 21.0, 0.7, 'Lutador', 'Nenhum', 'Psiquico, Voador e Fada', 'Hitmonlee, Hitmonchan ou Hitmontop', '2'),
	(237, 'Hitmontop', 48.0, 1.4, 'Lutador', 'Nenhum', 'Psiquico, Voador e Fada', 'N/A', '2'),
	(238, 'Smoochum', 6.0, 0.4, 'Gelo', 'Psiquico', 'Metal, Fantasma, Fogo, Escuridão, Pedra e Inseto', 'Jynx', '2'),
	(239, 'Elekid', 23.5, 0.6, 'Elétrico', 'Nenhum', 'Terra', 'Electabuzz', '2'),
	(240, 'Magby', 21.4, 0.7, 'Fogo', 'Nenhum', 'Agua, Terra e Pedra', 'Magmar', '2'),
	(241, 'Miltank', 75.5, 1.2, 'Normal', 'Nenhum', 'Lutador', 'N/A', '2'),
	(242, 'Blissey', 46.8, 1.5, 'Normal', 'Nenhum', 'Lutador', 'N/A', '2'),
	(243, 'Raikou', 178.0, 1.9, 'Elétrico', 'Nenhum', 'Terra', 'N/A', '2'),
	(244, 'Entai', 198.0, 2.1, 'Fogo', 'Nenhum', 'Agua, Terra e Pedra', 'N/A', '2'),
	(245, 'Suicune', 187.0, 2.0, 'Agua', 'Nenhum', 'Planta e Elétrico', 'N/A', '2'),
	(246, 'Larvitar', 72.0, 0.6, 'Pedra', 'Terra', 'Metal, Lutador, Agua, Gelo, Planta e Terra', 'Pupitar','2'),
	(247, 'Pupitar', 152.0, 1.2, 'Pedra', 'Terra', 'Metal, Lutador, Agua, Gelo, Planta e Terra', 'Tyranitar','2'),
	(248, 'Tyranitar', 202.0, 2.0, 'Pedra', 'Escuridão', 'Metal, Lutador, Agua, Fada, Planta, Inseto e Terra', 'N/A','2'),
	(249, 'Lugia', 216.0, 5.2, 'Psiquico', 'Voador', 'Fantasma, Escuridão, Elétrico, Gelo e Pedra', 'N/A','2'),
	(250, 'Ho-Oh', 199.0, 3.8, 'Fogo', 'Voador', 'Agua, Elétrico e Pedra', 'N/A','2'),
	(251, 'Celebi', 5.0, 0.6, 'Psiquico', 'Planta', 'Fantasma, Fogo, Voador, Gelo, Escuridão, Venenoso e Inseto', 'N/A','2'),
	
	  		                                        # Terceira Geração #

        (252, 'Treecko', 5.0, 0.5, 'Planta', 'Nenhum', 'Fogo, Voador, Gelo, Venonoso e Inseto', 'Grovyle','3'),
	(253, 'Grovyle', 21.6, 0.9, 'Planta', 'Nenhum', 'Fogo, Voador, Gelo, Venonoso e Inseto', 'Sceptile','3'),
	(254, 'Sceptile', 52.2, 1.7, 'Planta', 'Nenhum', 'Fogo, Voador, Gelo, Venonoso e Inseto', 'N/A','3'),
	(255, 'Torchic', 2.5, 0.4, 'Fogo', 'Nenhum', 'Agua, Terra e Pedra', 'Combusken','3'),
	(256, 'Combusken', 19.5, 0.9, 'Fogo', 'Lutador', 'Agua, Psiquico, Voador e Terra', 'Blaziken','3'),
	(257, 'Blaziken', 52.0, 1.9, 'Fogo', 'Lutador', 'Agua, Psiquico, Voador e Terra', 'N/A','3'),
	(258, 'Mudkip', 7.6, 0.4, 'Agua', 'Nenhum', 'Planta e Elétrico', 'Marshtomp', '3'),
	(259, 'Marshtomp', 28.0, 0.7, 'Agua', 'Terra', 'Planta e Elétrico', 'Swampert', '3'),
	(260, 'Swampert', 81.9, 1.5, 'Agua', 'Terra', 'Planta e Elétrico', 'N/A', '3'),
	(261, 'Poochyena', 13.6, 0.5, 'Escuridão', 'Nenhum', 'Fada, Inseto e Lutador', 'Mightyena', '3'),
	(262, 'Mightyena', 37.0, 1.0, 'Escuridão', 'Nenhum', 'Fada, Inseto e Lutador', 'N/A', '3'),
	(263, 'Zigzagoon', 17.5, 0.4, 'Normal', 'Nenhum', 'Lutador', 'Linoone', '3'),
	(264, 'Linoone', 32.5, 0.5, 'Normal', 'Nenhum', 'Lutador', 'N/A', '3'),
	(265, 'Wurmple', 3.6, 0.3, 'Inseto', 'Nenhum', 'Fogo, Voador e Pedra', 'Silcoon ou Cascoon', '3'),
	(266, 'Silcoon', 10.0, 0.6, 'Inseto', 'Nenhum', 'Fogo, Voador e Pedra', 'Beautifly', '3'),
	(267, 'Beautifly', 28.4, 1.0, 'Inseto', 'Voador', 'Fogo, Voador, Elétrico, Gelo e Pedra', 'N/A', '3'),
	(268, 'Cascoon', 11.5, 0.7, 'Inseto', 'Nenhum', 'Fogo, Voador e Pedra', 'Dustox', '3'),
	(269, 'Dustox', 31.6, 1.2, 'Inseto', 'Venenoso', 'Fogo, Psiquico, Voador e Pedra', 'N/A', '3'),
	(270, 'Lotad', 2.6, 0.5, 'Agua', 'Planta', 'Voador, Inseto e Venenoso', 'Lombre','3'),
	(271, 'Lombre', 32.5, 1.2, 'Agua', 'Planta', 'Voador, Inseto e Venenoso', 'Ludicolo','3'),
	(272, 'Ludicolo', 55.0, 1.5, 'Agua', 'Planta', 'Voador, Inseto e Venenoso', 'N/A','3'),
	(273, 'Seedot', 4.0, 0.5, 'Planta', 'Nenhum', 'Fogo, Voador, Gelo, Venonoso e Inseto', 'Nuzleaf','3'),
	(274, 'Nuzleaf', 28.0, 1.0, 'Planta', 'Escuridão', 'Gelo, Fogo, Voador, Venenoso, Lutador, Fada e Inseto', 'Shiftry','3'),
	(275, 'Shiftry', 59.6, 1.3, 'Planta', 'Escuridão', 'Gelo, Fogo, Voador, Venenoso, Lutador, Fada e Inseto', 'N/A','3'),
	(276, 'Taillow', 2.3, 0.3, 'Normal', 'Voador', 'Elétrico, Gelo e Pedra', 'Swellow', '3'),
	(277, 'Swellow', 19.8, 0.7, 'Normal', 'Voador', 'Elétrico, Gelo e Pedra', 'N/A', '3'),
	(278, 'Wingull', 9.5, 0.6, 'Normal', 'Agua', 'Elétrico e Pedra', 'Pelipper', '3'),
	(279, 'Pelipper', 28.0, 1.2, 'Normal', 'Agua', 'Elétrico e Pedra', 'N/A', '3'),
	(280, 'Ralts', 6.6, 0.4, 'Psiquico', 'Fada', 'Fantasma, Aço e Venenoso', 'Kirlia', '3'),
	(281, 'Kirlia', 20.2, 0.8, 'Psiquico', 'Fada', 'Fantasma, Aço e Venenoso', 'Gardevoir ou Gallade', '3'),
	(282, 'Gardevoir', 48.4, 1.6, 'Psiquico', 'Fada', 'Fantasma, Aço e Venenoso', 'N/A', '3'),
	(283, 'Surskit', 1.7, 0.5, 'Inseto', 'Agua', 'Voador, Elétrico e Pedra', 'Masquerain', '3'),
	(284, 'Masquerain', 3.6, 0.8, 'Inseto', 'Voador', 'Fogo, Voador, Elétrico, Gelo e Pedra', 'N/A', '3'),
	(285, 'Shroomish', 4.5, 0.4, 'Planta', 'Nenhum', 'Fogo, Voador, Gelo, Venonoso e Inseto', 'Breloom','3'),
	(286, 'Breloom', 39.2, 1.2, 'Planta', 'Lutador', 'Fogo, Psiquico, Voador, Gelo, Venonoso e Inseto', 'N/A','3'),
	(287, 'Slakoth', 24.0, 0.8, 'Normal', 'Nenhum', 'Lutador', 'Vigoroth', '3'),
	(288, 'Vigoroth', 46.5, 1.4, 'Normal', 'Nenhum', 'Lutador', 'Slaking', '3'),
	(289, 'Slaking', 130.5, 2.0, 'Normal', 'Nenhum', 'Lutador', 'N/A', '3'),
	(290, 'Nincada', 5.5, 0.5, 'Inseto', 'Terra', 'Fogo, Agua, Voador e Gelo', 'Ninjask ou Shedinja', '3'),
	(291, 'Ninjask', 12.0, 0.9, 'Inseto', 'Voador', 'Fogo, Voador, Elétrico, Gelo e Rocha', 'N/A', '3'),
        (292, 'Shedinja', 1.2, 0.8, 'Inseto', 'Fantasma', 'Fogo, Fantasma, Voador, Escuridão e Rocha', 'N/A', '3'),
	(293, 'Whismur', 16.3, 0.6, 'Normal', 'Nenhum', 'Lutador', 'Loudred', '3'),
	(294, 'Loudred', 40.5, 1.5, 'Normal', 'Nenhum', 'Lutador', 'Exploud', '3'),
	(295, 'Exploud', 84.0, 1.5, 'Normal', 'Nenhum', 'Lutador', 'N/A', '3'),
	(296, 'Makuhita', 86.4, 0.6, 'Lutador', 'Nenhum', 'Psiquico, Voador e Fada', 'Hariyama', '3'),
	(297, 'Hariyama', 253.8, 2.3, 'Lutador', 'Nenhum', 'Psiquico, Voador e Fada', 'N/A', '3'),
	(298, 'Azurill', 2.0, 0.2, 'Normal', 'Fada', 'Metal e Venenoso', 'Marill', '3'),
	(299, 'Nosepass', 97.0, 1.0, 'Pedra', 'Nenhum', 'Agua, Metal, Planta, Lutador e Terra', 'Probopass','3'),
	(300, 'Skitty', 11.0, 0.6, 'Normal', 'Nenhum', 'Lutador', 'Delcatty', '3'),
	(301, 'Delcatty', 32.6, 1.1, 'Normal', 'Nenhum', 'Lutador', 'N/A', '3'),
	(302, 'Sableye', 11.0, 0.5, 'Escuridão', 'Fantasma', 'Fada', 'N/A', '3'),
	(303, 'Mawile', 11.5, 0.6, 'Metal', 'Fada', 'Fogo e Terra', 'N/A', '3'),
	(304, 'Aron', 60.0, 0.4, 'Metal', 'Pedra', 'Agua, Lutador e Terra', 'Lairon', '3'),
	(305, 'Lairon', 120.0, 0.9, 'Metal', 'Pedra', 'Agua, Lutador e Terra', 'Aggron', '3'),
	(306, 'Lairon', 360.0, 2.1, 'Metal', 'Pedra', 'Agua, Lutador e Terra', 'N/A', '3'),
	(307, 'Meditite', 11.2, 0.6, 'Lutador', 'Psiquico', 'Fantasma, Fada e Voador', 'Medicham', '3'),
	(308, 'Medicham', 31.5, 1.3, 'Lutador', 'Psiquico', 'Fantasma, Fada e Voador', 'N/A', '3'),
	(309, 'Electrike', 15.2, 0.6, 'Elétrico', 'Nenhum', 'Terra', 'Manectric', '3'),
	(310, 'Manectric', 40.2, 1.5, 'Elétrico', 'Nenhum', 'Terra', 'N/A', '3'),
	(311, 'Plusle', 4.2, 0.4, 'Elétrico', 'Nenhum', 'Terra', 'N/A', '3'),
	(312, 'Minun', 4.2, 0.4, 'Elétrico', 'Nenhum', 'Terra', 'N/A', '3'),
	(313, 'Volbeat', 17.7, 0.7, 'Inseto', 'Nenhum', 'Fogo, Voador e Pedra', 'N/A', '3'),
	(314, 'Volbeat', 17.7, 0.6, 'Inseto', 'Nenhum', 'Fogo, Voador e Pedra', 'N/A', '3'),
	(315, 'Roselia', 2.0, 0.3, 'Planta', 'Venenoso', 'Fogo, Psiquico, Gelo e Voador', 'Roserade', '3'),
	(316, 'Gulpin', 10.3, 0.4, 'Venenoso', 'Nenhum', 'Psiquico e Terra', 'Swalot', '3'),
	(317, 'Swalot', 80.0, 1.7, 'Venenoso', 'Nenhum', 'Psiquico e Terra', 'N/A', '3'),
	(318, 'Carvanha', 20.8, 0.8, 'Agua', 'Escuridão', 'Fada, Planta, Elétrico, Lutador e Inseto', 'Sharpedo', '3'),
	(319, 'Sharpedo', 88.8, 1.8, 'Agua', 'Escuridão', 'Fada, Planta, Elétrico, Lutador e Inseto', 'N/A', '3'),
	(320, 'Wailmer', 130.0, 2.0, 'Agua', 'Nenhum', 'Planta e Elétrico', 'Wailord', '3'),
	(321, 'Wailord', 398.0, 14.5, 'Agua', 'Nenhum', 'Planta e Elétrico', 'N/A', '3'),
	(322, 'Numel', 24.0, 0.7, 'Fogo', 'Terra', 'Agua e Terra', 'Camerupt','3'),
	(323, 'Camerupt', 220.0, 1.9, 'Fogo', 'Terra', 'Agua e Terra', 'N/A','3'),
	(324, 'Torkoal', 80.4, 0.5, 'Fogo', 'Nenhum', 'Agua, Terra e Pedra', 'N/A','3'),
	(325, 'Spoink', 30.6, 0.7, 'Psiquico', 'Nenhum', 'Fantasma, Escuridão e Inseto', 'Grumpig','3'),
	(326, 'Grumpig', 71.5, 0.9, 'Psiquico', 'Nenhum', 'Fantasma, Escuridão e Inseto', 'N/A','3'),
	(327, 'Spinda', 5.0, 1.1, 'Normal', 'Nenhum', 'Lutador', 'N/A','3'),
	(328, 'Trapinch', 15.0, 0.7, 'Terra', 'Nenhum', 'Agua, Planta e Gelo', 'Vibrava','3'),
	(329, 'Vibrava', 15.3, 1.1, 'Terra', 'Dragão', 'Fada, Gelo e Dragão', 'Flygon','3'),
	(330, 'Flygon', 82.0, 2.0, 'Terra', 'Dragão', 'Fada, Gelo e Dragão', 'N/A','3'),
	(331, 'Cacnea', 51.3, 0.4, 'Planta', 'Nenhum', 'Fogo, Voador, Gelo Venenoso e Inseto', 'Cacturne','3'),
	(332, 'Cacturne', 77.4, 1.3, 'Planta', 'Escuridão', 'Gelo, Fogo, Voador, Venonoso, Lutador, Fada e Inseto', 'N/A','3'),
	(333, 'Swablu', 1.2, 0.4, 'Normal', 'Voador', 'Elétrico, Gelo e Pedra', 'Altaria', '3'),
	(334, 'Altaria', 1.1, 20.6, 'Dragão', 'Voador', 'Fada, Dragão, Gelo e Pedra', 'N/A', '3'),
	(335, 'Zangoose', 40.3, 1.3, 'Normal', 'Nenhum', 'Lutador', 'N/A', '3'),
	(336, 'Seviper', 52.5, 2.7, 'Venenoso', 'Nenhum', 'Psiquico e Terra', 'N/A', '3'),
	(337, 'Lunatone', 168.5, 1.0, 'Pedra', 'Psiquico', 'Metal, Fantasma, Agua, Escuridão, Planta, Inseto e Terra', 'N/A', '3'),
	(338, 'Solrock', 154.0, 1.2, 'Pedra', 'Psiquico', 'Metal, Fantasma, Agua, Escuridão, Planta, Inseto e Terra', 'N/A', '3'),
	(339, 'Barboach', 1.9, 0.4, 'Agua', 'Terra', 'Grama', 'Whiscash', '3'),
	(340, 'Whiscash', 23.6, 0.9, 'Agua', 'Terra', 'Grama', 'N/A', '3'),
	(341, 'Corphish', 11.5, 0.6, 'Agua', 'Nenhum', 'Planta e Elétrico', 'Crawdaunt', '3'),
	(342, 'Crawdaunt', 32.8, 1.1, 'Agua', 'Escuridão', 'Fada, Grama, Elétrico, Lutador e Inseto', 'N/A', '3'),
	(343, 'Baltoy', 21.5, 0.5, 'Terra', 'Psiquico', 'Fantasma, Agua, Gelo, Escuridão, Planta, Inseto', 'Claydol', '3'),
	(344, 'Claydol', 108.0, 1.5, 'Terra', 'Psiquico', 'Fantasma, Agua, Gelo, Escuridão, Planta, Inseto', 'N/A', '3'),
	(345, 'Lileep', 23.8, 1.0, 'Pedra', 'Planta', 'Metal, Gelo, Lutador e Inseto', 'Cradily', '3'),
	(346, 'Cradily', 60.4, 1.5, 'Pedra', 'Planta', 'Metal, Gelo, Lutador e Inseto', 'N/A', '3'),
	(347, 'Anorith', 12.5, 0.7, 'Pedra', 'Inseto', 'Metal, Agua e Pedra', 'Armaldo', '3'),
	(348, 'Armaldo', 68.2, 1.5, 'Pedra', 'Inseto', 'Metal, Agua e Pedra', 'N/A', '3'),
	(349, 'Feebas', 7.4, 0.6, 'Agua', 'Nenhum', 'Planta e Elétrico', 'Milotic', '3'),
	(350, 'Milotic', 162.0, 6.2, 'Agua', 'Nenhum', 'Planta e Elétrico', 'N/A', '3'),
	(351, 'Castform', 0.8, 0.3, 'Normal', 'Nenhum', 'Lutador', 'N/A', '3'),
	(352, 'Kecleon ', 22.0, 1.0, 'Normal', 'Nenhum', 'Lutador', 'N/A', '3'),
	(353, 'Shuppet', 2.3, 0.6, 'Fantasma', 'Nenhum', 'Fantasma e Escuridão', 'Banette', '3'),
	(354, 'Banette', 12.5, 1.1, 'Fantasma', 'Nenhum', 'Fantasma e Escuridão', 'N/A', '3'),
	(355, 'Duskull', 15.0, 0.8, 'Fantasma', 'Nenhum', 'Fantasma e Escuridão', 'Dusclops', '3'),
	(356, 'Dusclops', 30.6, 1.6, 'Fantasma', 'Nenhum', 'Fantasma e Escuridão', 'Dusknoir', '3'),
	(357, 'Tropius', 100.0, 2.0, 'Planta', 'Voador', 'Fogo, Voador, Gelo Venenoso e Pedra', 'N/A','3'),
	(358, 'Chimecho ', 1.0, 0.6, 'Psiquico', 'Nenhum', 'Fantasma, Escuridão e Inseto', 'N/A', '3'),
	(359, 'Absol', 47.0, 1.2, 'Escuridão', 'Nenhum', 'Fada, Inseto e Lutador', 'N/A', '3'),
	(360, 'Wynaut ', 14.0, 0.6, 'Psiquico', 'Nenhum', 'Fantasma, Escuridão e Inseto', 'Wobbuffet', '3'),
	(361, 'Snorunt ', 16.8, 0.7, 'Gelo', 'Nenhum', 'Fogo, Metal, Lutador e Pedra', 'Glalie ou Froslass', '3'),
	(362, 'Glalie ', 256.5, 1.5, 'Gelo', 'Nenhum', 'Fogo, Metal, Lutador e Pedra', 'N/A', '3'),
	(363, 'Spheal ', 39.5, 0.8, 'Gelo', 'Agua', 'Planta, Elétrico, Lutador e Pedra', 'Sealeo', '3'), # É o meu Preferido ❤️ #
	(364, 'Sealeo ', 87.6, 1.1, 'Gelo', 'Agua', 'Planta, Elétrico, Lutador e Pedra', 'Walrein', '3'),
	(365, 'Walrein ', 150.6, 1.4, 'Gelo', 'Agua', 'Planta, Elétrico, Lutador e Pedra', 'N/A', '3'),
	(366, 'Clamperl', 52.5, 0.4, 'Agua', 'Nenhum', 'Planta e Elétrico', 'Huntail ou Gorebyss', '3'),
	(367, 'Huntail', 27.0, 1.7, 'Agua', 'Nenhum', 'Planta e Elétrico', 'N/A', '3'),
	(368, 'Gorebyss', 22.6, 1.8, 'Agua', 'Nenhum', 'Planta e Elétrico', 'N/A', '3'),
	(369, 'Relicanth', 23.4, 1.0, 'Agua', 'Pedra', 'Planta, Elétrico, Lutador e Terra', 'N/A', '3'),
	(370, 'Luvdisc', 8.7, 0.6, 'Agua', 'Nenhum', 'Planta e Elétrico', 'N/A', '3'),
	(371, 'Bagon', 42.1, 0.6, 'Dragão', 'Nenhum', 'Fada, Gelo e Dragão', 'Shelgon', '3'),
	(372, 'Shelgon', 110.5, 1.1, 'Dragão', 'Nenhum', 'Fada, Gelo e Dragão', 'Salamence', '3'),
	(373, 'Salamence', 102.6, 1.5, 'Dragão', 'Voador', 'Fada, Dragão, Gelo e Pedra', 'N/A', '3'),
	(374, 'Beldum', 95.2, 0.6, 'Metal', 'Psiquico', 'Fantasma, Fogo, Escuridão e Terra', 'Metang', '3'),
	(375, 'Metang', 202.5, 1.2, 'Metal', 'Psiquico', 'Fantasma, Fogo, Escuridão e Terra', 'Metagross', '3'),
	(376, 'Metagross', 550.0, 1.6, 'Metal', 'Psiquico', 'Fantasma, Fogo, Escuridão e Terra', 'N/A', '3'),
	(377, 'Regirock', 230.0, 1.7, 'Pedra', 'Nenhum', 'Agua, Metal, Planta, Lutador e Terra', 'N/A', '3'),
	(378, 'Regice', 175.0, 1.8, 'Gelo', 'Nenhum', 'Fogo, Metal, Lutador e Pedra', 'N/A', '3'),
	(379, 'Registeel', 205.0, 1.9, 'Metal', 'Nenhum', 'Fogo, Lutador e Terra', 'N/A', '3'),
	(380, 'Latias', 40.0, 1.4, 'Dragão', 'Psiquico', 'Fantasma, Gelo, Dragão, Escuridão, Fada e Inseto', 'N/A', '3'),
	(381, 'Latios', 60.0, 2.0, 'Dragão', 'Psiquico', 'Fantasma, Gelo, Dragão, Escuridão, Fada e Inseto', 'N/A', '3'),
	(382, 'Kyogre', 352.0, 4.5, 'Agua', 'Nenhum', 'Planta e Elétrico', 'N/A', '3'),
	(383, 'Groudon', 950.0, 3.5, 'Terra', 'Nenhum', 'Agua, Planta e Gelo', 'N/A', '3'),
	(384, 'Rayquaza', 206.5, 7.0, 'Dragão', 'Voador', 'Fada, Dragão, Gelo e Pedra', 'N/A', '3'),
	(385, 'Jirachi', 1.1, 0.3, 'Metal', 'Psiquico', 'Fantasma, Fogo, Escuridão e Terra', 'N/A', '3'),
	(386, 'Deoxys', 60.8, 1.7, 'Psiquico', 'Nenhum', 'Fantasma, Escuridão e Inseto', 'N/A', '3');
	
                                                
